In [102]:
import numpy as np
import pandas as pd

a = np.arange(100, dtype=np.float64).reshape(10,10)
rep_count = 1000000
z = np.empty(rep_count)
print(a)

def work_func(*args):
    return args[0]+args[1]+args[2]

def with_tiles():
    a_tile = np.tile(a, (rep_count, 1))
    res = pd.DataFrame(work_func(*a_tile.T))
    print('tiles', res)
def with_bcast():
    _, a_broadcast = np.broadcast_arrays(z[:, np.newaxis, np.newaxis], a.T[np.newaxis, ...])
    #a_broadcast = a_broadcast.reshape(a.shape[0]*rep_count, a.shape[1])
    res = pd.DataFrame(work_func(*a_broadcast.transpose(1, 0, 2)))
    print('bcast', res)

[[  0.   1.   2.   3.   4.   5.   6.   7.   8.   9.]
 [ 10.  11.  12.  13.  14.  15.  16.  17.  18.  19.]
 [ 20.  21.  22.  23.  24.  25.  26.  27.  28.  29.]
 [ 30.  31.  32.  33.  34.  35.  36.  37.  38.  39.]
 [ 40.  41.  42.  43.  44.  45.  46.  47.  48.  49.]
 [ 50.  51.  52.  53.  54.  55.  56.  57.  58.  59.]
 [ 60.  61.  62.  63.  64.  65.  66.  67.  68.  69.]
 [ 70.  71.  72.  73.  74.  75.  76.  77.  78.  79.]
 [ 80.  81.  82.  83.  84.  85.  86.  87.  88.  89.]
 [ 90.  91.  92.  93.  94.  95.  96.  97.  98.  99.]]


In [104]:
%memit with_tiles()
%memit with_bcast()

tiles            0
0          3
1         33
2         63
3         93
4        123
5        153
6        183
7        213
8        243
9        273
10         3
11        33
12        63
13        93
14       123
15       153
16       183
17       213
18       243
19       273
20         3
21        33
22        63
23        93
24       123
25       153
26       183
27       213
28       243
29       273
...      ...
9999970    3
9999971   33
9999972   63
9999973   93
9999974  123
9999975  153
9999976  183
9999977  213
9999978  243
9999979  273
9999980    3
9999981   33
9999982   63
9999983   93
9999984  123
9999985  153
9999986  183
9999987  213
9999988  243
9999989  273
9999990    3
9999991   33
9999992   63
9999993   93
9999994  123
9999995  153
9999996  183
9999997  213
9999998  243
9999999  273

[10000000 rows x 1 columns]
peak memory: 961.55 MiB, increment: 889.07 MiB
bcast         0   1   2   3    4    5    6    7    8    9
0       3  33  63  93  123  153  183  213  243  273
1 